sudo: required
dist: trusty
language: php

#versi php
php:
  - 7.1

#branch yang di gunakan
branches: 
  only: 
    - master #->  QA/Straging server
    - develop #-> DevServer

# instal Environmen di OS

# precompile
before_script :

# main execution proses build
script :
