sudo: required
dist: trusty
language: php

#versi php
php:
  -7.1

#branch yang di gunakan
branches : 
  only: 
    - master #->  QA/Straging server
    - develop #-> DevServer

# instal Environmen di OS

# precompile
before_script :
- cp .env.travis .env
  - composer install -no-interaction
  - php artisan key:generate

# main execution proses build
script :
  - ./vendor/bin/phpunit

#display
after_success :

